In [1]:
print("Hello, Python!")

Hello, Python!


In [2]:
! pip install numpy
! pip install pandas
! pip install scikit-learn

                                              0.0/10.6 MB ? eta -:--:--
     -                                        0.4/10.6 MB 13.1 MB/s eta 0:00:01
     ---                                      1.0/10.6 MB 12.5 MB/s eta 0:00:01
     -----                                    1.5/10.6 MB 12.1 MB/s eta 0:00:01
     -------                                  2.1/10.6 MB 12.1 MB/s eta 0:00:01
     ----------                               2.7/10.6 MB 12.1 MB/s eta 0:00:01
     ------------                             3.2/10.6 MB 12.1 MB/s eta 0:00:01
     --------------                           3.8/10.6 MB 12.2 MB/s eta 0:00:01
     ----------------                         4.4/10.6 MB 12.1 MB/s eta 0:00:01
     ------------------                       4.9/10.6 MB 12.1 MB/s eta 0:00:01
     --------------------                     5.5/10.6 MB 12.1 MB/s eta 0:00:01
     ----------------------                   6.1/10.6 MB 12.1 MB/s eta 0:00:01
     -------------------------                6.

In [7]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [8]:
import pandas as pd

In [9]:
# 붓꽃 데이터 세트를 로딩합니다
iris = load_iris()

In [11]:
iris_data = iris.data

In [12]:
iris_label = iris.target

In [13]:
# 붓꽃 데이터 세트를 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                5.1               3.5                1.4               0.2  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [14]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,test_size=0.2, random_state=11)

In [15]:
# 의사결정트리 모델
df_clf = DecisionTreeClassifier(random_state=11)

In [16]:
# 학습 수행
df_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [17]:
# 학습모델로 예측테스트
pred = df_clf.predict(X_test)

In [19]:
X_test

array([[6.8, 3. , 5.5, 2.1],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.4, 2.7, 5.3, 1.9],
       [4.9, 3.1, 1.5, 0.1],
       [6.7, 3.1, 4.4, 1.4],
       [5.7, 4.4, 1.5, 0.4],
       [4.8, 3.1, 1.6, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [6. , 2.2, 5. , 1.5],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [5.7, 2.5, 5. , 2. ],
       [6.9, 3.1, 5.4, 2.1],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 2.9, 5.6, 1.8],
       [5.6, 3. , 4.5, 1.5],
       [6.5, 3.2, 5.1, 2. ],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.5, 3.9, 1.1],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3.4, 1.6, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [5.4, 3.9, 1.3, 0.4],
       [6. , 3.4, 4.5, 1.6]])

In [21]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [22]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


In [24]:
new_data = [[5.1, 3.5, 1.4, 0.2], [6.2, 3.4, 5.4, 2.3]]
new_pred = df_clf.predict(new_data)

new_pred

array([0, 2])

In [25]:
import joblib
joblib.dump(df_clf, "model.joblib")

['model.joblib']

In [26]:
loaded_model = joblib.load("model.joblib")

In [27]:
loaded_model.predict(new_data)

array([0, 2])